feat: merge more config

diff --git a/functions/z b/functions/z
--- a/functions/z
+++ b/functions/z
@@ -1,23 +1,24 @@
 #!/usr/bin/env bash
 
-choices="$(
-	find \
-		"${HOME}/dev" \
-		-mindepth 1 \
-		-maxdepth 2 \
-		-type d &&
-	find \
-		"/tmp/mount/" \
-		-mindepth 1 \
-		-maxdepth 1 \
-		-type d &&
-	find \
-		"${HOME}" \
-		-mindepth 1 \
-		-maxdepth 1 \
-		-type d \
-)"
+TODO: add this as well
+	# find \
+	# 	"/tmp/mount/" \
+	# 	-mindepth 1 \
+	# 	-maxdepth 1 \
+	# 	-type d &&
 
-cd "$(
-	echo "${choices}" | fzf --select-1 --query "${*}"
-)" || exit
+selection=$(
+	{
+		git-repos
+		find "${HOME}" -maxdepth 1 -mindepth 1 -type d | sed "s#^${HOME}#~#"
+	} | fzf --select-1 --query "${*}"
+)
+
+[ -z "${selection}" ] && return
+
+# no expansion of ~ is ok
+# shellcheck disable=2088
+case "${selection}" in
+	"~/"*) cd "${selection/#\~/${HOME}}" || { echo "z: cd failed: ${selection}" >&2; return 1; } ;;
+	*) cd "$(git-worktree -p --repo "${DEV_PATH}/${selection}")" || { echo "z: cd failed: ${selection}" >&2; return 1; } ;;
+esac
